# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Daguo's blog
# subtitle: '达哥的博客'
subtitle: 'Hello guy, welcome!'
description: 'Personal blog which build by hexo from shudery/daguo'
author: Daguo
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://shudery.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false # 把链接改为与根目录的相对位置
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

category_generator:
  per_page: 10

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can custmeomize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 1000
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
theme: chic

# Extensions
## Plugins: http://hexo.io/plugins/
#RSS订阅`
plugin:
  - hexo-generator-feed
# - hexo-generator-baidu-sitemap
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20
#sitemap
# baidusitemap:
# path: baidusitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:shudery/shudery.github.io.git
  # repo: git@git.coding.net:shudery/shudery.git
  branch: master
  # branch: coding-pages

# social accounts
github: 'https://github.com/shudery'
douban: 'https://www.douban.com/people/shudery/'
zhihu: 'https://www.zhihu.com/people/shudery/activities'
twitter: 'https://twitter.com/Linshudery'
